from infrastructure.config.postgres_config import connection_pool
from infrastructure.repositories_impl.postgres.postgres_companies_repository import PostgresCompaniesRepository
from infrastructure.repositories_impl.postgres.postgres_mailing_repository import PostgresMailingRepository
from infrastructure.repositories_impl.postgres.postgres_users_repository import PostgresUsersRepository
from infrastructure.repositories_impl.postgres.postgres_task_repository import PostgresTasksRepository
from infrastructure.repositories_impl.postgres.postgres_user_chats_repository import PostgresUserChatsRepository
from infrastructure.repositories_impl.postgres.postgres_group_chats_repository import PostgresGroupChatsRepository
from infrastructure.repositories_impl.postgres.postgres_meetings_repository import PostgresMeetingsRepository
from infrastructure.repositories_impl.postgres.postgres_messages_repository import PostgresMessagesRepository
from infrastructure.repositories_impl.postgres.postrges_arbitrary_user_data_repository import PostgresArbitaryUserDataRepository
from infrastructure.repositories_impl.postgres.postgres_ctrls_repository import PostgresCtrlsRepository

users_rep = PostgresUsersRepository(connection_pool)
companies_rep = PostgresCompaniesRepository(connection_pool)
tasks_rep = PostgresTasksRepository(connection_pool, users_repository=users_rep)
meetings_rep = PostgresMeetingsRepository(connection_pool, users_repository=users_rep)
messages_rep = PostgresMessagesRepository(connection_pool, users_rep)
user_chats_rep = PostgresUserChatsRepository(connection_pool)
group_chats_rep = PostgresGroupChatsRepository(connection_pool)
mailing_rep = PostgresMailingRepository(connection_pool)
arbitrary_rep = PostgresArbitaryUserDataRepository(connection_pool)
ctrls_rep = PostgresCtrlsRepository(connection_pool)